spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/quiz_db
    username: chetan
    password: root@123

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true

jwt:
  secret: sfdsaxwer2gsdbygsdfgsygf634t63453wdfsgfhvabdsfvsa
  expiration: 86400000

server:
  port: 8080

cloud:
  s3:
    bucket: Chetan-Bucket
    endpoint: https://s3.us-east-005.backblazeb2.com
    access-key: 005343905bf577c0000000001
    secret-key: K005h4CEp0XNVk2DPGuJQpvdMnjmZn0
    region: us-east-005